refactor: pub visibility modifier
penumbra-zone/decaf377 pull request #95
Opened 2024-02-26 17:55 UTC by TalDerei

This is required, otherwise the monorepo will complain about some wrapper functions being private associated functions.

2024-02-26 18:08 UTC, cronokirby requested changes
from_montgomery_limbs and from_raw_bytes shouldn't be exposed. The former is impossible to use correctly unless you really know the constants and what's going on internally. The latter should be replaced with the _mod_order version that's already exposed.

2024-03-03 18:18 UTC, TalDerei commented
exposed `to_le_limbs` and renamed `from_le_limbs` to `from_le_limbs_mod_order` for clarity.

2024-03-07 23:53 UTC, cronokirby commented
We absolutely do not want to allow doing that, instead, we should use the Fq::SENTINEL value

2024-04-02 21:29 UTC, redshiftzero commented
We realized while modifying poseidon377 to work in embedded environments (ref: https://github.com/penumbra-zone/poseidon377/pull/53) that we'll need `Fq::from_montgomery_limbs` to be `pub` in order to instantiate Fq constants. Upon discussion in Discord with @cronokirby it makes sense to add a disclaimer to the `Fq::from_montgomery_limb` methods that this should not be used unless you are familiar with the internals of the library.

2024-04-17 16:12 UTC, closed without merging

2024-04-17 16:12 UTC, TalDerei commented
closing in favor of #98